{% set version = "2.2.0" %}

package:
  name: user-agents
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/user-agents/user-agents-{{ version }}.tar.gz
  sha256: d36d25178db65308d1458c5fa4ab39c9b2619377010130329f3955e7626ead26

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ua-parser >=0.10.0

test:
  imports:
    - user_agents
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/selwin/python-user-agents
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A library to identify devices (phones, tablets) and their capabilities by parsing (browser/HTTP) user agent strings
  dev_url: https://github.com/selwin/python-user-agents

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
