appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bBsiE13sVyuhRjAFa0fBA4GbGQCKIGN83i6XQQQsr03jUJRpkZrG6WHT+/lMi3OJWzcA7Z0uf70yZiqMMMcx7hVt5lDzz8+i7PCescfc7WIaCN9TdRhW0VT5dr3q2xpLy7NIfg1xFTKDQ9Vi27wKu1+rz7bd964aFUAdDld2vethZ6kUv55rdh9vEDZ+rOweOS59jUFf8hC37hRJ80mhdVPJlr7bMqf0lz24zv9nA2ZA2cE5gbocL7UXdgmGqmW9jZKltjZnXexwq3rJb6y9G9ok0YdNuvZoVrnxmqORkx31tM2uq27mPgiLQP8+lcJlDuIuBUhqA5BZLa2ggiMHUndSBYauIsXyh8SlLYuo6MZ/lXQX1zzl0jr97Mwd2Gl9psG9C/6yOcT/OlBwLatsKC4esOc/lUXou5TrTLTCPSRyrjLr6FEIs5xKjMgAl3DN/QlFxPLXX0GkyGYIOl2329VEcOL5HY52yKe2gfZuUM7j19iMiiUdv5sRYSW6YKj/o+BFj6C8bYBWW7mavp//H2n4oDuU/nKmwm/nLxHM1GtG9DheJ42NDYK8hfEHNO6lLnu/Jel7VRpGxCwj/kRDdQhzq3XfRhwiU/JyTWU6a5bp4Wuk+y6tL1f2UbbnwLqGhDFqXxMkMw6xnnRrrTyNHC75dFqIep7QPt/FAktk5Xg=}
